apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBcz5Y1ukO8PLKDcTXeRBxF/UABn2UWoxmO/RIgT+rfzxBVRHwJggo8jyC9CdOiABxY6RUyT5PxXUYxqJXoi/HU6jTAWAA1F2C0Lr03jOIJpzW4j9g7bKbxH/SVzM/FyUi8bH9lf9ZHRNqaGGg1nq2HqTpkW9mrlWYm1/y1S0KxKOwP41ODqJLR0W+OVRkDxdu6uT3/ldpyY6ajktHl17fkDdepPRIHy2BE8AKcaxzr7P1wBJMnDCVVVqOPxauZM6VQ+6qry6J8oYO1eWK1MUklAXkn1h5cpdD212b3/ySnAhpd2JMelFmB4eG2IPiqTmiCkewXfG73Ov7plzuupicGj/mIBeJ7iRnKjpYbeBT8sG3Fg6cw+wvhkVGV7gAwLt9rxA8hIX8FoXM+m3L25atDMEGbo+V+ZQ2ngzYZlJEng81tDnaPNxbBqlWxwMCNTbvfqePepHEowDuUh0gk65EzJ9I5IixM4Jfc18BovshXht0oTR8GLeSufi3Qzj5yWgwI3nTzgVbbS7ncVRFlaIbUYumq+2rdjXtS4cnyGUT2IszJwJ0OhHoaeCWoI++a3mbmtvvG2uxAGgimmxbnF9bFcVgea+wkO+g9LmpTis1/KpltW1AEvRAq1I4C1MveNZXbNnLGH/Qi5RITzgzlRAYjT8oHpLcgvJJGR3ZGfBNVBV4dwbNED6b2C3MtEN3NXsb6DAzCN7wBHA==
    DB_USER: AgAar1JcBJeGPKF+nL8gA9LariXPpEbp56/Ia/E5PMnmW/nSaYMQ/fNC3WIRvO5zYkXEbVxlc9f41MzT0YBUwh0cYFf8BoObCnUP1Pp/DOlcfXpboFm3yR4NqVN+HXIRRFY8E4kqtnyJ5TTEb/ZKZMEDNBOXixhHuy5zkrnbe3EapZ9PxWdkkzBefeB24dE7gSVBOsh/rXIacJq3Wiwk32uRou4tWg2IkwSEgOPVEHyUffek7JGLxqzyYCh27c+kG1Oqg1FxB65Yc5Y5P05dtvIuuuKNWwyPQuKeeIHy7Cvb3cFPDVNdPCd8CRYS2l0PGPmfspKTTBFjFwA3Eu2kc0Z5IJKQRsykYDngt6MqqyI7FzHaWVU4cpIHOFAEruI3elylN+yUbKG/qCJkCoYL9hOFOSqR/QY7e4S6B8tUX4v5W3X5Xsin7YW5UDkCxS0JZRYx3DgOakA7PtFX2aSSnbJem1cNR5uHBucv+t0v93p3T9mchZ8ByQEl7j2NJnyRvJyo4JpfMUWrRCotiwmNweYu0VrxRmQ+RBaqnPwD6MdxgUwtgr3OTCBflKi6Vey3KOEtQvjHGCdEdtCDeBqmfPLjsDm+v/Pg2bFkMB2wLZ0g/zQ7V5XOM530zsYL70se1U5IX5dh2Bnnbp579AmSqEHtqYYwS/SiWcxUE8MyCvd5YlMQmbEFauWPO1vvr9cZqdMXakD756Sq5A==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

